# Generated by Django 6.0.3 on 2026-04-08 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_set1', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(help_text='e.g. icici-uae', unique=True)),
                ('api_base_url', models.URLField(blank=True, max_length=255, null=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('provider_class_path', models.CharField(help_text='Full path to provider class, e.g. api_set1.services.providers.NID.ICICIProvider', max_length=255)),
                ('icon_name', models.CharField(default='fas fa-building', help_text='FontAwesome icon name', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Comparison Company',
                'verbose_name_plural': 'Comparison Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_type', models.CharField(choices=[('health', 'Health Insurance'), ('travel', 'Travel Insurance'), ('motor', 'Motor Insurance'), ('home', 'Home Insurance')], max_length=50)),
                ('age', models.IntegerField()),
                ('sum_insured', models.DecimalField(decimal_places=2, max_digits=12)),
                ('city', models.CharField(max_length=100)),
                ('members', models.IntegerField(default=1)),
                ('additional_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('hdfc', 'HDFC Ergo'), ('icici', 'ICICI Lombard'), ('star', 'Star Health')], max_length=50)),
                ('premium', models.DecimalField(decimal_places=2, max_digits=12)),
                ('coverage', models.DecimalField(decimal_places=2, max_digits=12)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('comparison_score', models.FloatField(default=0)),
                ('is_best', models.BooleanField(default=False)),
                ('response_time_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='api_set1.quoterequest')),
            ],
            options={
                'ordering': ['-comparison_score'],
                'unique_together': {('quote_request', 'provider')},
            },
        ),
    ]
