# Generated by Django 6.0.3 on 2026-04-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_set1', '0003_corporatecustomer_deal_individualcustomer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='competitive_advantages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quote',
            name='scoring_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quote',
            name='verdict',
            field=models.TextField(blank=True, null=True),
        ),
    ]
