# Generated by Django 6.0.3 on 2026-04-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_set1', '0004_quote_competitive_advantages_quote_scoring_breakdown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='colour',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='vehicle_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='name_arabic',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name (Arabic)'),
        ),
    ]
