# Generated by Django 6.0.3 on 2026-04-10 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_set1', '0005_deal_colour_deal_vehicle_value_lead_name_arabic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusoverview',
            options={'ordering': ['-date'], 'verbose_name': 'Status Overview'},
        ),
        migrations.CreateModel(
            name='InsuranceCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_code', models.CharField(max_length=50)),
                ('cover_name', models.CharField(max_length=255)),
                ('cover_type', models.CharField(choices=[('mandatory', 'Mandatory'), ('optional', 'Optional')], max_length=20)),
                ('premium', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covers', to='api_set1.quote')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(blank=True, max_length=100, null=True)),
                ('net_premium', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_url', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selected_scheme', to='api_set1.quote')),
            ],
        ),
    ]
