# Generated by Django 6.0.3 on 2026-04-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_set1', '0006_alter_statusoverview_options_insurancecover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='provider_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Stored provider-specific data (e.g. Reference No)'),
        ),
        migrations.AlterField(
            model_name='insuranceprovider',
            name='provider_class_path',
            field=models.CharField(help_text='Full path to provider class, e.g. api_set1.services.providers.NID.NIAProvider', max_length=255),
        ),
    ]
